region                          = "ap-south-1"
bucketname                      = "qa_t1t2t3hhhdcdc"
project_name                    = "qa"
snsname                         = "test-sns"
sqsname                         = "test-sqs"
accountid                       = "876313778020"